name: 'Deployment review comment'
description: 'Extract the deployment review comment specified as part of Manual approval/rejection of a workflow execution'
branding:
  icon: 'list'
  color: 'blue'
inputs:  
  token:
    description: 'GitHub token'
    required: true    
  run-id:
    type: string
    description: 'Run id of the workflow'
    required: false  
output:
  comments:
    description: 'Array of deployment review comments along with state and environment'

runs:
  using: 'node16'
  main: 'app/index.js'